<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../EutherDrive.UI/Rendering/PublishedFrameBuffer.cs" Link="PublishedFrameBuffer.cs" />
    <Compile Include="../../EutherDrive.UI/Rendering/LatestPresentationRequest.cs" Link="LatestPresentationRequest.cs" />
  </ItemGroup>
</Project>
