#!/usr/bin/env sh
set -eu

ROM_PATH="${1:-/home/nichlas/roms/MAME/Midway/Vegas/gauntd}"
CONFIGURATION="${EUTHERDRIVE_GAUNTDL_PROBE_CONFIG:-Release}"
SNAPSHOT="${EUTHERDRIVE_GAUNTDL_WARMUP_STATE:-/tmp/eutherdrive-gauntlet-probe/gauntdl-qio-metadata-200m.warm}"
EXTRA_SERIES="${EUTHERDRIVE_GAUNTDL_EXTRA_SERIES:-1000000,5100000,20000000}"
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"

cd "$REPO_ROOT"

DLL="tools/GauntletProbe/bin/${CONFIGURATION}/net8.0/GauntletProbe.dll"

export EUTHERDRIVE_GAUNTDL_BRINGUP_FAST=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_DISPLAY_BUFFER=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_FASTFILL_COLOR_MASK=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_BGLOADMODEL_QIO_REQUEST_METADATA=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_WORLD_SELECTION=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_BGLOADMODEL_QIO_HYDRATE=1
export EUTHERDRIVE_GAUNTDL_FASTPATH_DIAGNOSTIC_RUNTIME=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_DIAGNOSTIC_OVERLAY_SUPPRESS=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_DIAGNOSTIC_TEXT_PUMP_SKIP=1
export EUTHERDRIVE_GAUNTDL_FASTPATH_RUNTIME_BGLOADMODEL_EXPERIMENTAL=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_VERTEX_FIFO_EMIT=1
export EUTHERDRIVE_GAUNTDL_WARMUP_STATE="$SNAPSHOT"
export EUTHERDRIVE_GAUNTDL_EXTRA_SERIES="$EXTRA_SERIES"

if [ -f "$DLL" ]; then
    exec dotnet "$DLL" "$ROM_PATH" 300 0 0
fi

exec dotnet run --project tools/GauntletProbe/GauntletProbe.csproj -c "$CONFIGURATION" --no-restore -- "$ROM_PATH" 300 0 0
