#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"

ROM_PATH="${1:-/home/nichlas/roms/MAME/Midway/Vegas/gauntd}"
TARGET_FRAMES="${2:-6770}"
CPU_STEPS="${3:-60000}"
SNAPSHOT_PATH="${4:-$REPO_ROOT/.build-tmp/gaunt-k2-clean2-f6750.warm.gz}"
SNAPSHOT_FRAMES="${5:-6750}"
PROBE_DLL="$REPO_ROOT/tools/GauntletProbe/bin/Release/net8.0/GauntletProbe.dll"

if [ ! -f "$SNAPSHOT_PATH" ]; then
    echo "Gauntlet warm snapshot not found: $SNAPSHOT_PATH" >&2
    exit 1
fi
if [ ! -f "$PROBE_DLL" ]; then
    echo "Release GauntletProbe build missing." >&2
    exit 1
fi

export EUTHERDRIVE_GAUNTDL_CPU_STEPS_PER_FRAME="$CPU_STEPS"
export EUTHERDRIVE_GAUNTDL_BRINGUP_BASELINE=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_RGB_BUFFER_MASK=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_MAME_VBLANK_SWAP_TIMING=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_MAME_MEDIUM_RES_OUTPUT=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_SETUP_MAME_AUX_DEPTH=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_SUPPRESS_IMPLAUSIBLE_SETUP_TRIANGLES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_SUPPRESS_IMPLAUSIBLE_BULK_DIRECT_TRIANGLES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_TEXTURE_LOD_MIN_REGISTER_BASE=0x1a0df
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_GLIDE_WINOPEN_RGB_MASK=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_WORLD_LIST_INVALID_SENTINEL_END=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_GAME_TASK=0
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_SUPPRESS_DIAGNOSTIC_RENDER_ENABLE=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_COUNTER_WAIT_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_TRANSFORM_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_RENDER_CHAIN_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_TABLE_CLEAR_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_SAFE_INSTRUCTION_BATCHES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_SAFE_BRANCH_PAIRS="${EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_SAFE_BRANCH_PAIRS:-1}"
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_STANDARD_FIFO_DECODE_COMPLETE_PACKETS=1
export EUTHERDRIVE_GAUNTDL_PARALLEL_VOODOO_TEXTURE_RASTER="${EUTHERDRIVE_GAUNTDL_PARALLEL_VOODOO_TEXTURE_RASTER:-1}"
export EUTHERDRIVE_GAUNTDL_WARMUP_STATE="$SNAPSHOT_PATH"
export EUTHERDRIVE_GAUNTDL_WARMUP_FRAMES="$SNAPSHOT_FRAMES"
export EUTHERDRIVE_GAUNTDL_LOAD_WARMUP_IGNORE_CPU_STEPS=1

unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_FORCE_RENDER_BUFFER_INDEX
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_PRESERVE_PRESENTED_BUFFER_WITHOUT_DRAW
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_COMPOSITE_BACK_BUFFER_OVER_COHERENT_FRAME
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_COMPOSITE_BASE_BUFFER_INDEX
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_COMPOSITE_LIVE_BUFFER_INDEX
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_NATIVE_INPUT_POLL
unset EUTHERDRIVE_GAUNTDL_EXTRA_SERIES

exec dotnet "$PROBE_DLL" "$ROM_PATH" "$TARGET_FRAMES" "$CPU_STEPS" 0
