#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"

ROM_PATH="${1:-/home/nichlas/roms/MAME/Midway/Vegas/gauntd}"
SNAPSHOT_PATH="${2:-$REPO_ROOT/.build-tmp/gaunt-k2-clean2-f6750.warm.gz}"
SNAPSHOT_FRAMES="${3:-6750}"
CPU_STEPS="${4:-90000}"
UI_DLL="$REPO_ROOT/EutherDrive.UI/bin/Release/net8.0/EutherDrive.UI.dll"
PROBE_DLL="$REPO_ROOT/tools/GauntletProbe/bin/Release/net8.0/GauntletProbe.dll"

if [ ! -f "$SNAPSHOT_PATH" ]; then
    echo "Gauntlet warm snapshot not found: $SNAPSHOT_PATH" >&2
    exit 1
fi
if [ ! -f "$UI_DLL" ] || [ ! -f "$PROBE_DLL" ]; then
    echo "Release UI or GauntletProbe build missing; build both Release projects first." >&2
    exit 1
fi

export EUTHERDRIVE_GAUNTDL_CPU_STEPS_PER_FRAME="$CPU_STEPS"
export EUTHERDRIVE_GAUNTDL_BRINGUP_BASELINE=1
# Keep the desktop profile identical to the validated probe for the Voodoo
# paths which are not part of the core's compact baseline preset.
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_RGB_BUFFER_MASK=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_MAME_VBLANK_SWAP_TIMING=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_MAME_MEDIUM_RES_OUTPUT=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_SETUP_MAME_AUX_DEPTH=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_SUPPRESS_IMPLAUSIBLE_SETUP_TRIANGLES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_SUPPRESS_IMPLAUSIBLE_BULK_DIRECT_TRIANGLES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_TEXTURE_LOD_MIN_REGISTER_BASE=0x1a0df
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_GLIDE_WINOPEN_RGB_MASK=1
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_WORLD_LIST_INVALID_SENTINEL_END=1
# This checkpoint contains the native live game loop in main state 0x400f and
# the disk-owned levelK2 texture residency reconstructed from gauntd24.raw.
# It starts on the ship with the player active and avoids the stale phase-1
# TMU banks carried by the earlier journey checkpoint.
# Player input remains live and no prerecorded input is applied after reload.
# Starting the synthetic fallback task would duplicate the imported RTOS task.
export EUTHERDRIVE_GAUNTDL_FIX_RUNTIME_GAME_TASK=0
# With command FIFO enabled, Voodoo 2 ignores direct writes to FIFO-able
# registers. The queued swap is therefore the only real rotation; no stale
# presented-buffer preservation is needed.
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_FORCE_RENDER_BUFFER_INDEX
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_PRESERVE_PRESENTED_BUFFER_WITHOUT_DRAW
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_COMPOSITE_BACK_BUFFER_OVER_COHERENT_FRAME
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_COMPOSITE_BASE_BUFFER_INDEX
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_COMPOSITE_LIVE_BUFFER_INDEX
# The live RTOS path now reaches the real input normalizer without a synthetic
# callback, which keeps player updates in their original guest context.
unset EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_NATIVE_INPUT_POLL
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_SUPPRESS_DIAGNOSTIC_RENDER_ENABLE=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_COUNTER_WAIT_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_TRANSFORM_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_RENDER_CHAIN_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_TABLE_CLEAR_REGION=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_SAFE_INSTRUCTION_BATCHES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_SAFE_BRANCH_PAIRS=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_DIRECT_BRANCH_PAIRS=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_MERGE_BRANCH_PAIRS=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_COMPILED_BLOCKS=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_GUARDED_TRACES=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_RENDER_SETUP_GUARDED_TRACE=1
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_RUNTIME_RENDER_SUBMIT_GUARDED_TRACE=1
export EUTHERDRIVE_GAUNTDL_FIX_VOODOO_STANDARD_FIFO_DECODE_COMPLETE_PACKETS=1
export EUTHERDRIVE_GAUNTDL_PARALLEL_VOODOO_TEXTURE_RASTER="${EUTHERDRIVE_GAUNTDL_PARALLEL_VOODOO_TEXTURE_RASTER:-1}"
export EUTHERDRIVE_GAUNTDL_EXPERIMENT_VOODOO_PROFILED_COMMON_RASTER_KERNEL=1
export EUTHERDRIVE_GAUNTDL_UI_WARMUP_STATE="$SNAPSHOT_PATH"
export EUTHERDRIVE_GAUNTDL_UI_WARMUP_FRAMES="$SNAPSHOT_FRAMES"
export EUTHERDRIVE_GAUNTDL_UI_WARMUP_IGNORE_CPU_STEPS=1
export EUTHERDRIVE_GAUNTDL_UI_FORCE_SPEED_LOCK=1
export EUTHERDRIVE_GAUNTDL_UI_SPEED_SCALE=1.0
export EUTHERDRIVE_GAUNTDL_PROBE_DLL="$PROBE_DLL"

exec dotnet "$UI_DLL" "$ROM_PATH"
